spring.application.name=Geoscience-RAG-Assistant


# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/geoscience_rag
spring.datasource.username=postgres
spring.datasource.password=Sumit@1137

# JPA / Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB
# Server
server.port=8080

qdrant.host=localhost
qdrant.port=6334